# Generated by Django 5.2.15 on 2026-06-19 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.EmailField(db_column='EMAIL', max_length=254, unique=True)),
                ('password', models.CharField(db_column='PASSWORD', max_length=255)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], db_column='ROLE', default='customer', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=200)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', default='')),
                ('price', models.BigIntegerField(db_column='PRICE', default=0)),
                ('stock', models.IntegerField(db_column='STOCK', default=0)),
                ('image', models.TextField(blank=True, db_column='IMAGE', default='')),
                ('is_active', models.BooleanField(db_column='IS_ACTIVE', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('category', models.ForeignKey(blank=True, db_column='CATEGORY_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('token', models.CharField(db_column='TOKEN', max_length=255)),
                ('device_label', models.CharField(db_column='DEVICE_LABEL', max_length=200)),
                ('ip_address', models.CharField(blank=True, db_column='IP_ADDRESS', default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('expires_at', models.DateTimeField(db_column='EXPIRES_AT')),
                ('last_used', models.DateTimeField(db_column='LAST_USED')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to='app.user')),
            ],
            options={
                'db_table': 'trusted_device',
            },
        ),
        migrations.CreateModel(
            name='OtpSession',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='EMAIL', default='', max_length=254)),
                ('code', models.CharField(db_column='CODE', max_length=6)),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('register', 'Register')], db_column='PURPOSE', max_length=20)),
                ('attempts', models.IntegerField(db_column='ATTEMPTS', default=0)),
                ('is_used', models.BooleanField(db_column='IS_USED', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('expires_at', models.DateTimeField(db_column='EXPIRES_AT')),
                ('user', models.ForeignKey(blank=True, db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_sessions', to='app.user')),
            ],
            options={
                'db_table': 'otp_session',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='EMAIL', default='', max_length=254)),
                ('event_type', models.CharField(db_column='EVENT_TYPE', max_length=50)),
                ('result', models.CharField(blank=True, db_column='RESULT', default='', max_length=20)),
                ('reason', models.CharField(blank=True, db_column='REASON', default='', max_length=100)),
                ('ip_address', models.CharField(blank=True, db_column='IP_ADDRESS', default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('user', models.ForeignKey(blank=True, db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='app.user')),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('product', models.ForeignKey(db_column='PRODUCT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app.product')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app.user')),
            ],
            options={
                'db_table': 'favorite',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(db_column='QUANTITY', default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('product', models.ForeignKey(db_column='PRODUCT_ID', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='app.product')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='app.user')),
            ],
            options={
                'db_table': 'cart_item',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
