# Generated by Django 5.2.15 on 2026-06-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('label', models.CharField(db_column='LABEL', default='Rumah', max_length=50)),
                ('recipient_name', models.CharField(db_column='RECIPIENT_NAME', max_length=150)),
                ('phone', models.CharField(db_column='PHONE', max_length=30)),
                ('address_line', models.TextField(db_column='ADDRESS_LINE')),
                ('city', models.CharField(db_column='CITY', max_length=100)),
                ('province', models.CharField(db_column='PROVINCE', max_length=100)),
                ('postal_code', models.CharField(db_column='POSTAL_CODE', max_length=10)),
                ('notes', models.CharField(blank=True, db_column='NOTES', default='', max_length=255)),
                ('is_default', models.BooleanField(db_column='IS_DEFAULT', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='app.user')),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
