# Generated by Django 5.2.15 on 2026-06-20 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('order_code', models.CharField(blank=True, db_column='ORDER_CODE', default='', max_length=30)),
                ('address_label', models.CharField(blank=True, db_column='ADDRESS_LABEL', default='', max_length=50)),
                ('recipient_name', models.CharField(db_column='RECIPIENT_NAME', max_length=150)),
                ('recipient_phone', models.CharField(db_column='RECIPIENT_PHONE', max_length=30)),
                ('address_line', models.TextField(db_column='ADDRESS_LINE')),
                ('city', models.CharField(db_column='CITY', max_length=100)),
                ('province', models.CharField(db_column='PROVINCE', max_length=100)),
                ('postal_code', models.CharField(db_column='POSTAL_CODE', max_length=10)),
                ('address_notes', models.CharField(blank=True, db_column='ADDRESS_NOTES', default='', max_length=255)),
                ('courier_name', models.CharField(db_column='COURIER_NAME', max_length=50)),
                ('shipping_fee', models.BigIntegerField(db_column='SHIPPING_FEE', default=0)),
                ('payment_method', models.CharField(db_column='PAYMENT_METHOD', max_length=30)),
                ('payment_target', models.CharField(blank=True, db_column='PAYMENT_TARGET', default='', max_length=100)),
                ('payment_proof', models.TextField(blank=True, db_column='PAYMENT_PROOF', default='')),
                ('payment_deadline', models.DateTimeField(blank=True, db_column='PAYMENT_DEADLINE', null=True)),
                ('payment_proof_uploaded_at', models.DateTimeField(blank=True, db_column='PAYMENT_PROOF_UPLOADED_AT', null=True)),
                ('subtotal', models.BigIntegerField(db_column='SUBTOTAL', default=0)),
                ('grand_total', models.BigIntegerField(db_column='GRAND_TOTAL', default=0)),
                ('status', models.CharField(choices=[('waiting_payment', 'Waiting Payment'), ('waiting_confirmation', 'Waiting Confirmation'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_column='STATUS', default='waiting_payment', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.user')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='PRODUCT_NAME', max_length=200)),
                ('product_price', models.BigIntegerField(db_column='PRODUCT_PRICE', default=0)),
                ('quantity', models.IntegerField(db_column='QUANTITY', default=1)),
                ('subtotal', models.BigIntegerField(db_column='SUBTOTAL', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('order', models.ForeignKey(db_column='ORDER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order')),
                ('product', models.ForeignKey(blank=True, db_column='PRODUCT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='app.product')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
    ]
