# Generated by Django 5.2.15 on 2026-06-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_deadline',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_proof_uploaded_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(
                choices=[
                    ('waiting_admin_approval', 'Waiting Admin Approval'),
                    ('pengemasan', 'Pengemasan'),
                    ('pengiriman', 'Pengiriman'),
                    ('selesai', 'Selesai'),
                ],
                db_column='STATUS',
                default='waiting_admin_approval',
                max_length=30,
            ),
        ),
    ]
