# Generated by Django 5.2.15 on 2026-06-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='is_active',
            field=models.BooleanField(db_column='IS_ACTIVE', default=True),
        ),
    ]
