# Generated by Django 5.2.15 on 2026-06-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_trusteddevice_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='login_id',
            field=models.CharField(blank=True, db_column='LOGIN_ID', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='login_id',
            field=models.CharField(blank=True, db_column='LOGIN_ID', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='otpsession',
            name='login_id',
            field=models.CharField(blank=True, db_column='LOGIN_ID', default='', max_length=64),
        ),
    ]
