# Generated by Django 5.2.15 on 2026-06-21 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_login_id_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMonitoring',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('login_id', models.CharField(blank=True, db_column='LOGIN_ID', default='', max_length=64)),
                ('device_label_snapshot', models.CharField(blank=True, db_column='DEVICE_LABEL_SNAPSHOT', default='', max_length=200)),
                ('trusted_device_status', models.CharField(
                    choices=[
                        ('usual', 'Yang Biasa Dipakai'),
                        ('known_rare', 'Dikenal Tapi Jarang Dipakai'),
                        ('new_trusted', 'Trusted Device Baru'),
                        ('not_registered', 'Tidak Ada di Trusted Device'),
                    ],
                    db_column='TRUSTED_DEVICE_STATUS',
                    default='not_registered',
                    max_length=30,
                )),
                ('trusted_device_created_at_snapshot', models.DateTimeField(blank=True, db_column='TRUSTED_DEVICE_CREATED_AT_SNAPSHOT', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('order', models.OneToOneField(db_column='ORDER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='app.order')),
                ('trusted_device', models.ForeignKey(blank=True, db_column='TRUSTED_DEVICE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_monitorings', to='app.trusteddevice')),
            ],
            options={
                'db_table': 'order_monitoring',
            },
        ),
    ]
