# Generated by Django 5.2.15 on 2026-06-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order_completion_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('return_code', models.CharField(blank=True, db_column='RETURN_CODE', default='', max_length=30, unique=True)),
                ('login_id', models.CharField(blank=True, db_column='LOGIN_ID', default='', max_length=64)),
                ('reason', models.TextField(blank=True, db_column='REASON', default='')),
                ('product_photo', models.TextField(blank=True, db_column='PRODUCT_PHOTO', default='')),
                ('ereceipt_proof', models.TextField(blank=True, db_column='ERECEIPT_PROOF', default='')),
                ('status', models.CharField(choices=[('waiting_admin_review', 'Waiting Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_column='STATUS', default='waiting_admin_review', max_length=30)),
                ('processed_at', models.DateTimeField(blank=True, db_column='PROCESSED_AT', null=True)),
                ('decision_reason', models.CharField(blank=True, db_column='DECISION_REASON', default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('order', models.OneToOneField(db_column='ORDER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='return_data', to='app.order')),
                ('processed_by', models.ForeignKey(blank=True, db_column='PROCESSED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_returns', to='app.user')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='app.user')),
            ],
            options={
                'db_table': 'returns',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_column='PRODUCT_NAME', max_length=200)),
                ('product_price', models.BigIntegerField(db_column='PRODUCT_PRICE', default=0)),
                ('ordered_quantity', models.IntegerField(db_column='ORDERED_QUANTITY', default=0)),
                ('quantity', models.IntegerField(db_column='QUANTITY', default=1)),
                ('subtotal', models.BigIntegerField(db_column='SUBTOTAL', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('order_item', models.ForeignKey(blank=True, db_column='ORDER_ITEM_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='app.orderitem')),
                ('product', models.ForeignKey(blank=True, db_column='PRODUCT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_items', to='app.product')),
                ('return_entry', models.ForeignKey(db_column='RETURN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.return')),
            ],
            options={
                'db_table': 'return_item',
            },
        ),
        migrations.CreateModel(
            name='ReturnMonitoring',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('login_id', models.CharField(blank=True, db_column='LOGIN_ID', default='', max_length=64)),
                ('device_label_snapshot', models.CharField(blank=True, db_column='DEVICE_LABEL_SNAPSHOT', default='', max_length=200)),
                ('trusted_device_status', models.CharField(choices=[('usual', 'Yang Biasa Dipakai'), ('known_rare', 'Dikenal Tapi Jarang Dipakai'), ('new_trusted', 'Trusted Device Baru'), ('not_registered', 'Tidak Ada di Trusted Device')], db_column='TRUSTED_DEVICE_STATUS', default='not_registered', max_length=30)),
                ('device_risk_score', models.IntegerField(db_column='DEVICE_RISK_SCORE', default=0)),
                ('failed_password_count', models.IntegerField(db_column='FAILED_PASSWORD_COUNT', default=0)),
                ('failed_password_score', models.IntegerField(db_column='FAILED_PASSWORD_SCORE', default=0)),
                ('failed_otp_count', models.IntegerField(db_column='FAILED_OTP_COUNT', default=0)),
                ('failed_otp_score', models.IntegerField(db_column='FAILED_OTP_SCORE', default=0)),
                ('order_device_label_snapshot', models.CharField(blank=True, db_column='ORDER_DEVICE_LABEL_SNAPSHOT', default='', max_length=200)),
                ('same_device_as_order', models.BooleanField(db_column='SAME_DEVICE_AS_ORDER', default=False)),
                ('device_mismatch_score', models.IntegerField(db_column='DEVICE_MISMATCH_SCORE', default=0)),
                ('hijack_risk_score', models.IntegerField(db_column='HIJACK_RISK_SCORE', default=0)),
                ('account_age_days', models.IntegerField(db_column='ACCOUNT_AGE_DAYS', default=0)),
                ('recent_returns_30d_count', models.IntegerField(db_column='RECENT_RETURNS_30D_COUNT', default=0)),
                ('recent_returns_90d_count', models.IntegerField(db_column='RECENT_RETURNS_90D_COUNT', default=0)),
                ('frequent_return_score', models.IntegerField(db_column='FREQUENT_RETURN_SCORE', default=0)),
                ('return_after_completion_minutes', models.IntegerField(db_column='RETURN_AFTER_COMPLETION_MINUTES', default=0)),
                ('rapid_return_score', models.IntegerField(db_column='RAPID_RETURN_SCORE', default=0)),
                ('new_account_return_score', models.IntegerField(db_column='NEW_ACCOUNT_RETURN_SCORE', default=0)),
                ('return_abuse_score', models.IntegerField(db_column='RETURN_ABUSE_SCORE', default=0)),
                ('total_risk_score', models.IntegerField(db_column='TOTAL_RISK_SCORE', default=0)),
                ('trusted_device_created_at_snapshot', models.DateTimeField(blank=True, db_column='TRUSTED_DEVICE_CREATED_AT_SNAPSHOT', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('return_entry', models.OneToOneField(db_column='RETURN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='monitoring', to='app.return')),
                ('trusted_device', models.ForeignKey(blank=True, db_column='TRUSTED_DEVICE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_monitorings', to='app.trusteddevice')),
            ],
            options={
                'db_table': 'return_monitoring',
            },
        ),
    ]
