# Generated by Django 5.2.15 on 2026-06-25 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_return_returnitem_returnmonitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='account_holder_name',
            field=models.CharField(blank=True, db_column='ACCOUNT_HOLDER_NAME', default='', max_length=150),
        ),
        migrations.AddField(
            model_name='return',
            name='account_number',
            field=models.CharField(blank=True, db_column='ACCOUNT_NUMBER', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='return',
            name='bank_name',
            field=models.CharField(blank=True, db_column='BANK_NAME', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_address',
            field=models.ForeignKey(blank=True, db_column='EXCHANGE_ADDRESS_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_entries', to='app.address'),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_address_label',
            field=models.CharField(blank=True, db_column='EXCHANGE_ADDRESS_LABEL', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_address_line',
            field=models.TextField(blank=True, db_column='EXCHANGE_ADDRESS_LINE', default=''),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_address_notes',
            field=models.CharField(blank=True, db_column='EXCHANGE_ADDRESS_NOTES', default='', max_length=255),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_city',
            field=models.CharField(blank=True, db_column='EXCHANGE_CITY', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_courier_name',
            field=models.CharField(blank=True, db_column='EXCHANGE_COURIER_NAME', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_phone',
            field=models.CharField(blank=True, db_column='EXCHANGE_PHONE', default='', max_length=30),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_postal_code',
            field=models.CharField(blank=True, db_column='EXCHANGE_POSTAL_CODE', default='', max_length=10),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_province',
            field=models.CharField(blank=True, db_column='EXCHANGE_PROVINCE', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_recipient_name',
            field=models.CharField(blank=True, db_column='EXCHANGE_RECIPIENT_NAME', default='', max_length=150),
        ),
        migrations.AddField(
            model_name='return',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('refund', 'Refund'), ('exchange', 'Exchange')], db_column='RESOLUTION_TYPE', default='', max_length=20),
        ),
        migrations.AddField(
            model_name='returnmonitoring',
            name='exchange_address_age_minutes',
            field=models.IntegerField(db_column='EXCHANGE_ADDRESS_AGE_MINUTES', default=0),
        ),
        migrations.AddField(
            model_name='returnmonitoring',
            name='exchange_address_mismatch_score',
            field=models.IntegerField(db_column='EXCHANGE_ADDRESS_MISMATCH_SCORE', default=0),
        ),
        migrations.AddField(
            model_name='returnmonitoring',
            name='exchange_address_risk_score',
            field=models.IntegerField(db_column='EXCHANGE_ADDRESS_RISK_SCORE', default=0),
        ),
        migrations.AddField(
            model_name='returnmonitoring',
            name='exchange_address_same_as_order',
            field=models.BooleanField(db_column='EXCHANGE_ADDRESS_SAME_AS_ORDER', default=False),
        ),
        migrations.AddField(
            model_name='returnmonitoring',
            name='exchange_new_address_score',
            field=models.IntegerField(db_column='EXCHANGE_NEW_ADDRESS_SCORE', default=0),
        ),
    ]
