# Generated by Django 5.2.15 on 2026-06-25 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_return_account_holder_name_return_account_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnEReceiptVerification',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('valid', 'Valid'), ('invalid', 'Invalid')], db_column='STATUS', default='', max_length=10)),
                ('failure_reason', models.TextField(blank=True, db_column='FAILURE_REASON', default='')),
                ('pdf_order_code', models.CharField(blank=True, db_column='PDF_ORDER_CODE', default='', max_length=30)),
                ('receipt_id', models.CharField(blank=True, db_column='RECEIPT_ID', default='', max_length=30)),
                ('customer_name', models.CharField(blank=True, db_column='CUSTOMER_NAME', default='', max_length=150)),
                ('customer_email', models.CharField(blank=True, db_column='CUSTOMER_EMAIL', default='', max_length=254)),
                ('total', models.BigIntegerField(db_column='TOTAL', default=0)),
                ('generated_at', models.DateTimeField(blank=True, db_column='GENERATED_AT', null=True)),
                ('file_name', models.CharField(blank=True, db_column='FILE_NAME', default='', max_length=255)),
                ('verified_at', models.DateTimeField(blank=True, db_column='VERIFIED_AT', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('return_entry', models.OneToOneField(db_column='RETURN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='ereceipt_verification', to='app.return')),
                ('verified_by', models.ForeignKey(blank=True, db_column='VERIFIED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_return_ereceipts', to='app.user')),
            ],
            options={
                'db_table': 'return_ereceipt_verification',
            },
        ),
    ]
