# Generated by Django 5.2.15 on 2026-06-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_returnereceiptverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnmonitoring',
            name='ereceipt_risk_score',
            field=models.IntegerField(db_column='ERECEIPT_RISK_SCORE', default=0),
        ),
    ]
