# Generated by Django 5.2.15 on 2026-06-25 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_returnmonitoring_ereceipt_risk_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='otp_verified_for_action',
            field=models.BooleanField(db_column='OTP_VERIFIED_FOR_ACTION', default=False),
        ),
        migrations.CreateModel(
            name='AdminReturnActionSession',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_column='SESSION_ID', max_length=64, unique=True)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject')], db_column='ACTION', max_length=20)),
                ('decision_reason', models.CharField(blank=True, db_column='DECISION_REASON', default='', max_length=255)),
                ('decision_risk_score', models.IntegerField(db_column='DECISION_RISK_SCORE', default=0)),
                ('decision_risk_level', models.CharField(blank=True, db_column='DECISION_RISK_LEVEL', default='', max_length=10)),
                ('otp_required', models.BooleanField(db_column='OTP_REQUIRED', default=False)),
                ('otp_verified', models.BooleanField(db_column='OTP_VERIFIED', default=False)),
                ('is_completed', models.BooleanField(db_column='IS_COMPLETED', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('completed_at', models.DateTimeField(blank=True, db_column='COMPLETED_AT', null=True)),
                ('admin_user', models.ForeignKey(db_column='ADMIN_USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='admin_return_action_sessions', to='app.user')),
                ('return_entry', models.ForeignKey(db_column='RETURN_ID', on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_sessions', to='app.return')),
            ],
            options={
                'db_table': 'admin_return_action_session',
            },
        ),
    ]
