# Generated by Django 5.2.15 on 2026-06-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_return_otp_verified_for_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_column='COMPLETED_AT', null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='completed_by',
            field=models.ForeignKey(blank=True, db_column='COMPLETED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_returns', to='app.user'),
        ),
        migrations.AddField(
            model_name='return',
            name='exchange_shipment_tracking',
            field=models.CharField(blank=True, db_column='EXCHANGE_SHIPMENT_TRACKING', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='return',
            name='received_at',
            field=models.DateTimeField(blank=True, db_column='RECEIVED_AT', null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='received_by',
            field=models.ForeignKey(blank=True, db_column='RECEIVED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to='app.user'),
        ),
        migrations.AddField(
            model_name='return',
            name='refund_proof',
            field=models.TextField(blank=True, db_column='REFUND_PROOF', default=''),
        ),
        migrations.AddField(
            model_name='return',
            name='return_courier_name',
            field=models.CharField(blank=True, db_column='RETURN_COURIER_NAME', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='return',
            name='return_tracking_number',
            field=models.CharField(blank=True, db_column='RETURN_TRACKING_NUMBER', default='', max_length=100),
        ),
        migrations.AddField(
            model_name='return',
            name='shipped_back_at',
            field=models.DateTimeField(blank=True, db_column='SHIPPED_BACK_AT', null=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('waiting_admin_review', 'Waiting Admin Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('shipped_back', 'Shipped Back'), ('received', 'Received'), ('completed', 'Completed')], db_column='STATUS', default='waiting_admin_review', max_length=30),
        ),
    ]
