# Generated by Django 5.2.15 on 2026-06-25 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_return_completed_at_return_completed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnmonitoring',
            name='ereceipt_risk_score',
        ),
    ]
